import * as React from "react";
import { Typography } from "antd";

import "./../style/page.learn-more.scss";

const { Title } = Typography;
export const LearnMorePage = (props) => {
  return (
    <div className="page learn-more-page">
      <Title className="main-title">Password Tester</Title>
      <div className="main-content">
        <p className="important">
          Read it before taking <b>Password Tester</b> seriously
        </p>
        <p>
          There are so many methods to hijack or hack someone's online account.
          One of those methods is <b>Brute Forcing</b>. These calculations
          mainly focus on the Brute Forcing method.
        </p>
        <p>
          Password Tester relies on a{" "}
          <b>third-party open-source program named @zxcvbn-ts/zxcvbn</b> to
          calculate the strength of a password.
        </p>
        <p>
          Please note that these calculations (the strength, crack times,
          warning and suggestions) are also calculated and generated by the
          above mentioned program. This web app just enables you to use that
          program with ease.
        </p>
        <p>
          <b>Also note that these calculations might be wrong.</b> Because it
          assumes that the hacker/brute-forcer/the person trying to crack your
          password, doesn't know anthing about you. But mostly this is not the
          case, they gather data about you as much as possible.
        </p>
      </div>
    </div>
  );
};
