import * as React from "react";
import { Typography } from "antd";

import "./../style/page.learn-more.scss";

const { Title } = Typography;
export const LearnMorePage: React.FC = () => {
	return (
		<div className="page learn-more-page">
			<Title className="main-title">Password Tester</Title>
			<div className="main-content">
				<p>
					There are so many methods to hijack or hack someone&apos;s online
					account. One of those methods is <b>Brute Forcing</b>. Brute forcing
					is &quot;trying out every available combination as the password&quot;.
					But also keep in mind that, hackers also use a specific word-list
					instead of trying out all combinations.
				</p>
				<p>
					Password Tester&apos;s calculations are mainly focused on the Brute
					Forcing method. Because other methods are hard to predict and there
					are so many factors involved in it.
				</p>
				<p>
					Password Tester relies on a{" "}
					<b>third-party open-source program named @zxcvbn-ts/zxcvbn</b> to
					calculate the strength of a password. Note that all calculations (the
					strength, crack times, warning and suggestions) are calculated and
					generated by the above mentioned program. This web app just enables
					you to use that program with ease.
				</p>
				<p>
					<b>Also note that these calculations might be wrong.</b> Because it
					assumes that the hacker/brute-forcer/the person trying to crack your
					password, doesn&apos;t know anthing about you. But mostly this is not
					the case, they gather data about you as much as possible. And then
					they create a word-list for you. So{" "}
					<b className="important">
						Don&apos;t use your name, birthday as your password
					</b>{" "}
					because that would be the first options in their word list.
				</p>
				<p>
					<b>@zxcvbn-ts/zxcvbn</b> gives 4 crack-times. And this web app shows
					the fastest and the slowest only.
				</p>
			</div>
		</div>
	);
};
